<nav class="menu2">
    <ol>Додати
        <li><a href="/Admin/AddProduct">Додати товар</a></li>
        <li><a href="/Admin/AddType">Додати тип товару</a></li>
        <li><a href="/Admin/AddVariation">Додати підтип товару</a></li>
        <li><a href="/Admin/DellProduct/">Видалити товар</a></li>
        <li><a href="/Admin/DellType">Видалити тип товару</a></li>
        <li><a href="/Admin/DellVariation">Видалити підтип товару</a></li>
        
    </ol>
    <ol>База
        <li><a href="/Admin/Search">Пошук по замовленням</a></li>
    </ol>
</nav>