<div class="about">
    <div class="aboutUs">
        <h2>About <span>Our Company</span></h2>
        <p>
            The Landscaper is a full-service landscaping company with a straightforward and unique design/build philosophy. We believe in having one landscape designer handle the job from its conception on paper, to the realization on your property. 
        </p>
        <p>
The Landscaper is made up of a group of highly skilled landscaping professionals who pays a lot of attention to small details. In the 30+ years of experience our staff keep your property looking and functioning beautifully. Our landscapers are fully licensed

The reason; by doing this you are able to communicate and work with a single individual, where you can share your thoughts and idea's with to bring them, in collaboration.
        </p>
        <p>
            The Landscaper is a full-service landscaping company with a straightforward and unique design/build philosophy. We believe in having one landscape designer handle the job from its conception on paper, to the realization on your property. The reason; by doing this you are able to communicate and work with a single individual, where you can share your thoughts and idea's with to bring them, in collaboration, to life. 
        </p>
        <p>
            The Landscaper is a full-service landscaping company with a straightforward and unique design/build philosophy. We believe in having one landscape designer handle the job from its conception on paper, to the realization on your property. The reason; by doing this you are able to communicate and work with a single individual, where you can share your thoughts and idea's with to bring them, in collaboration, to life. 
        </p>
    </div>
    <div class="form">
        <h2>Request <span>An Estimate</span></h2>
        <form action="/Home" method="post">
            <input type="text" name="name" class="inp" placeholder="Ваше ім'я" required>
            <input type="text" name="mail" class="inp" placeholder="E-Mail" required>
            <select name="types" id="types">
                <?php
                    $pdo = Connect::getConnect();
                    $obj = $pdo->prepare("select * from Types");
                    $obj->execute();
                    $list = $obj->fetchAll();
                    foreach($list as $item)
                    {
                        echo"<option value='".$item['Id']."'>".$item['Name']."</option>";
                    }
                ?>
            </select>
            <textarea name="description" id="ds" cols="30" rows="10" required></textarea>
            <input type="submit" name="send" value="Відправити" class="btn">
        </form>
    </div>
</div>