<!doctype html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <title>МСНП</title>
    
    <link rel="shortcut icon" href="/images/ic.ico" type="image/x-icon">

    
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link href="/css/default.css" rel="stylesheet" type="text/css" />
    <link href="/css/modal.css" rel="stylesheet" type="text/css" />
		
    <script src="/js/jquery-1.10.2.min.js"></script>
    
    <script src="/js/jquery.js" type="text/javascript"></script>
    <script src="/js/mobilyslider.js" type="text/javascript"></script>
    <script src="/js/init.js" type="text/javascript"></script>
    
</head>
<body>