<div id="content">
		
		<div class="slider">
			<div class="sliderContent">
				<div class="item">
					<img src="/images/img1.jpg" alt="" />
				</div>
				<div class="item">
					<img src="/images/img2.jpg" alt="" />
				</div>
				<div class="item">
					<img src="/images/img3.jpg" alt="" />
				</div>
				<div class="item">
					<img src="/images/img4.jpg" alt="" />
				</div>
				<div class="item">
					<img src="/images/img5.jpg" alt="" />
				</div>
				<div class="item">
					<img src="/images/img6.jpg" alt="" />
				</div>
			</div>
		</div>
<p style="text-align: center; font-size: 18px;"><b>Адреса:</b></p>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2493.191580163303!2d28.826348315397873!3d51.325995979605764!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNTHCsDE5JzMzLjYiTiAyOMKwNDknNDIuNyJF!5e0!3m2!1suk!2sua!4v1487424877035" width="600" height="450" frameborder="0" style="position: relative; border:0; left: 200px;" allowfullscreen></iframe>
<br><br><br><p style="text-align: center; font-size: 18px;"><b>Контакти:</b></p><br>
<p style="text-align: center;">(041-48)4-36-34</p>
<p style="text-align: center;">+380(67)26-26-865</p>
</div>
