<div class="autorization">
    <form action="/Account/Login" method="post" enctype="multipart/form-data" class="login">
        <p><input type="text" name="login" id="login" required placeholder="Лоґін"></p>
        <p><input type="password" name="pass" id="pass" required placeholder="Пароль"></p>
        <p><input id="form" type="submit" name="logs" value="Увійти" class="btn"></p>
        <p><a href="/Account/Registration">Реєстрація</a></p>
    </form>
</div>